# Generated by Django 3.0.5 on 2020-04-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatForex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10, verbose_name='シンボル')),
                ('date', models.DateField(verbose_name='日')),
                ('open', models.FloatField(verbose_name='始値')),
                ('high', models.FloatField(verbose_name='高値')),
                ('low', models.FloatField(verbose_name='安値')),
                ('close', models.FloatField(verbose_name='終値')),
                ('volume', models.IntegerField(verbose_name='出来高')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'dat_forex',
            },
        ),
    ]
